const { tgconn, buildInstalledQuerySchema, autoGeneratedSchema, getGraphQLSchema } = require('./src/index');
const cred = require('./test/config');
const express = require('express');
const { graphqlHTTP } = require('express-graphql');
const { getToken } = require('./src/tg_connection');


const app = express();


const generateSchema = async () => {

  const token = await getToken(cred.SECRET, cred.HOST);

  tgconn(cred.HOST, cred.GRAPH, cred.USERNAME, cred.PASSWORD, cred.SECRET, token);

  await autoGeneratedSchema();

  /**
   * when query from TigerGraph installed query, 
   * user can get vertex type from schema's function getVerticesObjectsDict()
   */
  const typeDefs = `
 scalar JSON
 type edgeSet {
   attributes: JSON
   directed: Boolean
   e_type: String
   from_id: String
   to_id: String
   from_type:String
   to_type: String
 }

 type Query {
   getClaims(inputPrescriber: String!, TGQueryResultName: String): [edgeSet]
 }
`;

  let queryName = ['getClaims'];
  buildInstalledQuerySchema(typeDefs, queryName);

  app.use('/graphql', graphqlHTTP({
    schema: getGraphQLSchema(),
    graphiql: true
  }));

  const port = process.env.PORT || 4000;

  app.listen(port, () => {
    console.log('Server is running');
  });
}

generateSchema();

